<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<<<<<<< HEAD
<testsuite hostname="asplapggnr1" name="Test" tests="2" failures="1" timestamp="21 Feb 2017 08:44:45 GMT" time="0.402" errors="0">
  <testcase name="Test01" time="0.361" classname="testScript.DemoTestClass"/>
=======
<testsuite hostname="asplapggnr1" name="Test" tests="2" failures="1" timestamp="20 Feb 2017 08:38:56 GMT" time="0.424" errors="0">
  <testcase name="Test01" time="0.399" classname="testScript.DemoTestClass"/>
>>>>>>> branch 'master' of https://github.com/Harveer-Singh/Yatra_Automation.git
  <testcase name="Test02" time="0.006" classname="testScript.DemoTestClass">
    <failure type="java.lang.AssertionError" message="Test case has been failed check log for details!!">
      <![CDATA[java.lang.AssertionError: Test case has been failed check log for details!!
	at utils.Log.fail(Log.java:551)
	at testScript.DemoTestClass.Test02(DemoTestClass.java:32)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- Test02 -->
</testsuite> <!-- Test -->
