<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
    <line>
      <![CDATA[<div class="test-result"><br><font color="green"><strong> test case has passed  </strong></font> </div>&emsp;]]>
    </line>
    <line>
      <![CDATA[<!--FAIL-->]]>
    </line>
    <line>
      <![CDATA[<div class="test-result"><br><font color="red"><strong> Test case has been failed check log for details!! </strong></font> </div>&emsp;]]>
    </line>
  </reporter-output>
  <suite name="Suite" duration-ms="402" started-at="2017-02-21T08:44:44Z" finished-at="2017-02-21T08:44:45Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="402" started-at="2017-02-21T08:44:44Z" finished-at="2017-02-21T08:44:45Z">
      <class name="testScript.DemoTestClass">
        <test-method status="PASS" signature="Test01()[pri:0, instance:testScript.DemoTestClass@3c5a99da]" name="Test01" duration-ms="361" started-at="2017-02-21T14:14:44Z" finished-at="2017-02-21T14:14:45Z">
          <reporter-output>
            <line>
              <![CDATA[<div class="test-result"><br><font color="green"><strong> test case has passed  </strong></font> </div>&emsp;]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test01 -->
        <test-method status="FAIL" signature="Test02()[pri:0, instance:testScript.DemoTestClass@3c5a99da]" name="Test02" duration-ms="6" started-at="2017-02-21T14:14:45Z" finished-at="2017-02-21T14:14:45Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Test case has been failed check log for details!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Test case has been failed check log for details!!
	at org.testng.Assert.fail(Assert.java:94)
	at utils.Log.fail(Log.java:551)
	at testScript.DemoTestClass.Test02(DemoTestClass.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:659)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:845)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1153)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1199)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1032)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[<!--FAIL-->]]>
            </line>
            <line>
              <![CDATA[<div class="test-result"><br><font color="red"><strong> Test case has been failed check log for details!! </strong></font> </div>&emsp;]]>
            </line>
          </reporter-output>
        </test-method> <!-- Test02 -->
      </class> <!-- testScript.DemoTestClass -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
